---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install Node.js using apt"
  become: yes
  apt: 
    name: nodejs

- name: "check node version"
  command: node -v
  register: result


- name: "install npm"
  become: yes
  apt:
    name: npm
